apiVersion: v1
kind: Service
metadata:
  name: {{ include "klite.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "klite.labels" . | nindent 4 }}
  {{- with mustMerge (dict) .Values.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: kafka
      port: {{ .Values.service.port }}
      targetPort: kafka
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "klite.selectorLabels" . | nindent 4 }}
